name: tsec
description: A new Flutter project for QR code management.

publish_to: 'none' # Keeps the project private.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  barcode_widget: ^2.0.1
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  http: ^1.0.0
  qr_flutter: ^4.1.0
  qr: ^3.0.1
  collection: ^1.16.0
  scrollable_tab_view: ^1.0.9
  shared_preferences: ^2.0.6
  flutter_native_splash: ^2.3.7
  animated_splash_screen: ^1.3.0
  permission_handler: ^11.0.1
  flutter_launcher_icons: ^0.13.1
  connectivity_plus: ^5.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/tsec.jpeg"
  android_icon_size: 120  # تعيين الحجم على Android
  ios_icon_size: 120  # تعيين الحجم على iOS
  android_icon_shape: "circle"  # تحديد شكل دائري للأيقونة على Android
  ios_icon_shape: "circle"  # تحديد شكل دائري للأيقونة على iOS

